[package]
name = "subreddit-dumper"
version = "0.1.0"
authors = ["Florian Brucker <mail@florianbrucker.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roux = "1.3.2"
tokio = { version = "1", features = ["full"] }
